%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullSupplier
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL, true).




-endif.


