%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_InvalidAddress
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_InvalidAddress').
-ic_compiled("4_4").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0",
                   "InvalidAddress",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_InvalidAddress".



