%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_AlreadyBound
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_AlreadyBound').
-ic_compiled("4_4").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",
                   "AlreadyBound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0".

%% returns name
name() -> "CosNaming_NamingContext_AlreadyBound".



