%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_HRL).
-define(OE_COS_NAMING_HRL, true).




-endif.


