%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ChannelNotFound
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ChannelNotFound').
-ic_compiled("4_4").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ChannelNotFound:1.0",
                   "ChannelNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ChannelNotFound:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ChannelNotFound".



