%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_StructuredProxyPullConsumer
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLCONSUMER_HRL, true).




-endif.


