%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_UnsupportedFilterableData
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_UnsupportedFilterableData').
-ic_compiled("4_4").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0",
                   "UnsupportedFilterableData",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0".

%% returns name
name() -> "CosNotifyFilter_UnsupportedFilterableData".



