%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ProxyNotFound
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ProxyNotFound').
-ic_compiled("4_4").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ProxyNotFound:1.0",
                   "ProxyNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ProxyNotFound:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ProxyNotFound".



