%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPushSupplier
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL, true).




-endif.


