%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Coordinator
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_COORDINATOR_HRL).
-define(COSTRANSACTIONS_COORDINATOR_HRL, true).




-endif.


