%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CORBA
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/orber/src/CORBA.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(CORBA_HRL).
-define(CORBA_HRL, true).




-endif.


