%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_OrberIFR
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ORBERIFR_HRL).
-define(OE_ORBERIFR_HRL, true).




-endif.


