%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_SynchronizationUnavailable
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_SynchronizationUnavailable').
-ic_compiled("4_4").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0",
                   "SynchronizationUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0".

%% returns name
name() -> "CosTransactions_SynchronizationUnavailable".



