%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent
%% Source: /var/lib/openshift/556f9860e0b8cdaf36000016/diy/otp/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_HRL).
-define(COSTIMEREVENT_HRL, true).


-record('CosTimerEvent_TimerEventT', {utc, event_data}).


-endif.


